Escape error message header
nameko/nameko-grpc pull request #51
Opened 2023-04-03 14:20 UTC by stephenc-pace

When a server raises an unhandled exception we catch it as a GrpcError message and pass it along in the grpc-message header. This header field is restricted to mostly printable ASCII characters + Space.

https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#requests

We need to percent encode this value (and reverse) when returning from client.

This doesn't appear to cause any issues with the nameko reference tests but we discovered it in production when returning tracebacks due to new lines. Linkerd fails to decode the header so it sends a GO_AWAY with error code 1 which causes nameko to shutdown the connection immedietly. 

The load testing GHZ also fails to decode the header when it contains invalid characters (Eg, a new line)
```
Error distribution:
  [1]   rpc error: code = Internal desc = invalid header field value for "grpc-message" 
```

2023-04-03 14:54 UTC, stephenc-pace commented
@mattbennett

2023-04-06 11:40 UTC, mattbennett requested changes
Nice catch! Small suggestion on the function names.

2023-04-06 11:40 UTC, mattbennett commented on nameko_grpc/headers.py
> +def encode_grpc_message(message):
The names of this functions could be improved, I think.

"gRPC message" sounds like it refers to the `Message → *{binary octet}` part of the DATA frame. Actually what we're doing here is making a value safe to be included in gRPC headers.

Perhaps simply `quote_encode(value)` and `quote_decode(value)` are better signatures.

2023-06-20 08:14 UTC, stephenc-pace commented
@mattbennett 
Updated the function names.
We've had this in prod now for a while with success. Can we look at merging?

2023-06-21 13:24 UTC, iky approved these changes
:+1: Thanks @stephenc-pace!

2023-06-21 13:30 UTC, iky commented
@mattbennett the change requested is made and this is running on prod load for quite some time, so I think I can merge .)

2023-06-21 13:30 UTC, merged